### model
model_name_or_path: /mnt/zh/deepseekv3/dsr1_bf16
trust_remote_code: true

### method
finetuning_type: full

### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
save_dir: /mnt/zh/outputs/dsr1_mmlu/

### eval
batch_size: 2
