### model
model_name_or_path: /data/local/User/zihao/base_models/Qwen2.5-0.5B
trust_remote_code: true

### method
stage: sft
do_train: true
do_predict: false
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: ep_easy,ep_medium,ep_hard_positive_train,ep_hard_negative_train
template: qwen
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/local/User/zihao/entity_prediction/outputs/qwen2.5_0.5B_215k_0414_lr1e-7_e2_bsz64
logging_steps: 1
save_steps: 3371
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 64
gradient_accumulation_steps: 2
learning_rate: 1.0e-7
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.02
bf16: true
ddp_timeout: 180000000