### model
model_name_or_path: /data/local/User/zihao/base_models/Qwen2.5-0.5B
trust_remote_code: true

### method
stage: sft
do_train: true
do_predict: false
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: ep_hard_v2_exp
template: qwen
cutoff_len: 256
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/local/User/zihao/entity_prediction/outputs/qwen2.5_0.5B_hardv2_exp_lr5e-5_e2_bsz16
logging_steps: 1
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.02
bf16: true
ddp_timeout: 180000000