### model
model_name_or_path: /mnt/zh/qwen/Qwen3-30B-A3B/
trust_remote_code: true

### method
stage: sft
do_train: true
do_predict: false
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_gather_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
flash_attn: fa2

### dataset
dataset: qacv3_pre_ans_train
eval_dataset: qac_250302_test
template: qwen3
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/zh/qwen/qwen3_30BA3B_sft_qacv3_pre_ans_lr5e-5_e4
logging_steps: 1
save_strategy: epoch
plot_loss: true
overwrite_output_dir: False

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
