### model
model_name_or_path: /mnt/zh/qwen/QwQ-32B
trust_remote_code: true

### method
stage: sft
do_train: true
do_predict: false
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_gather_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
flash_attn: fa2

### dataset
dataset: qacv2.3.0317_enrich_Spanish_train,qacv2.3.0317_enrich_French_train,qacv2.3.0317_enrich_German_train,qacv2.3.0317_enrich_Italian_train,qacv2.3.0317_enrich_Japanese_train,qacv2.3.0317_enrich_Korean_train,qacv2.3.0317_enrich_Dutch_train,qacv2.3.0317_enrich_Brazilian_Portuguese_train,qacv2.3.0317_enrich_European_Portuguese_train,qacv2.3.0317_enrich_Swedish_train,qacv2.3.0317_enrich_train
eval_dataset: qac_250302_test
template: qwq
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/zh/qwen/qwq_sft_qacv2.3.0317_enrich_11ML_lr5e-7_e1
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 5.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

### predict
# temperature: 0.6
# top_p: 0.95
# top_k: 20
# per_device_eval_batch_size: 8
# predict_with_generate: true
