### model
model_name_or_path: /mnt/zh/deepseekv3/dsr1_bf16
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
deepspeed: examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: qac_250302_train
eval_dataset: qac_250302_test
template: deepseek_r1
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/zh/deepseekv3/dsr1_bf16_lora_sft_qac_250302
logging_steps: 1
save_steps: 8
plot_loss: true
overwrite_output_dir: true
report_to: wandb
run_name: dsr1_bf16_lora_sft_qac_250302

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 5.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0
bf16: true
ddp_timeout: 180000000